### ISSUE TITLE
Zookeeper Connection refused error

### ISSUE THREAD

**Issue by Sharathmk99** [axuan25/kaa-docker#4]
Hi,

Tried your docker-compose method, but i'm getting zookeeper connection refused error. I think when i see the tail of kaa node logs the zookeeper host name is taken as localhost. Please check and fix it.
Please find attached log when i run the docker compose method

[error.txt](https://github.com/axuan25/kaa-docker/files/311793/error.txt)

Thanks
Sharath

**Comment by axuan25** [comment]
Hello, Sharathmk99,

I am unable to reproduce your bug at this moment. My guess is that while docker-compose launches services based on dependency order, it does not yet have any way to do health checks to see if a service is ready. This is an upcoming feature in docker (see docker/docker pull #22719) and I am intending to implement health checks as soon as it is released.

Health checks can be tricky. Some people check to see if a port is open to determine whether a service is ready, but this does not work in all cases. This is what is currently used to wait for the SQL provider, but I intend to change it and create a specifically designed checks based on each provider. 

This goes for the noSQL service and Zookeeper as well. For Zookeeper, I will push an update to use ZK's "ruok" command until it responds "imok". However, as ZK can take a coma-separated node list, it will have to check each of them before launching kaa-node. I am still thinking about the best solution for this and am open to any suggestions!

While I try my best to push updates as soon as I can, this project is conducted during my free time, thus I would ask that you please bear with me here! In the meantime, could you please include your docker version, for documentation purposes? Secondly, do try running the image without compose and by linking it to already-run containers and let me know if you still encounter this problem. Once again, I am not encountering this issue here.

**Comment by Sharathmk99** [comment]
Sure I'll try without docker compose and I'll update here.

**Comment by axuan25** [comment]
Greetings,

Another update has been pushed, including the Docker image (cburr25/kaa:0.9.0).

A health check has been added for Zookeeper nodes. It will loop over all specified ZK nodes until one is reachable. Let me know if this fixes your issue.

Thanks!

**Comment by Sharathmk99** [comment]
Thanks man it's working... :+1:
